### ISSUE TITLE
Does anvil-connect server work via https?

### ISSUE THREAD

**Issue by JiCiT** [christiansmith/anvil-connect#76]
Everything works perfectly when accessing via http, but I get ERR_CONNECTION_CLOSED error when trying to access via https.  Maybe there is some configuration setting I'm missing?

**Comment by christiansmith** [comment]
We've been using a reverse proxy/load balancer in front of Anvil that handles SSL in production. Because of that, we haven't yet needed built in https support. Obviously, supporting this natively needs to be on the todo list. In the mean time, a configuration similar to [this](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins) for nginx should do the trick.

**Comment by JiCiT** [comment]
Thanks.  I'll figure out a proxying solution then.
