### ISSUE TITLE
Cannot run nv init

### ISSUE THREAD

**Issue by JiCiT** [christiansmith/anvil-connect#77]
I was able to work around this, but nv init wouldn't work for me and I think I know why.  The nv tool requires the lib/cli directory, a few files in there require boot/settings, and that has this:
```javascript
require(path.join(cwd, 'config', env + '.json'))
```
A new empty directory isn't going to have the config files yet, of course, so running nv fails.

**Comment by christiansmith** [comment]
So sorry. I broke it in the last release. Pushing the fix shortly.

**Comment by christiansmith** [comment]
FYI release 0.1.30 does NOT fix the problem. It makes it worse. This is what I get for pushing code without being properly caffeinated :) 

Working on it.

**Comment by JiCiT** [comment]
:-) No worries.  It wasn't that big a deal.  I know how easy it is for stuff like that to go missed until someone else points it out.

**Comment by christiansmith** [comment]
Try 0.1.31. 

Also, recently started working on a [rewrite of the CLI as a separate package](https://github.com/christiansmith/anvil-connect-cli) using [nash](https://github.com/scottcorgan/nash).  Building a CLI framework, as it turns out, is not something I have the time or inclination to do. After talking to @scottcorgan about nash and Divshot's cli on [readthesource.io](http://hangouts.readthesource.io/hangouts/nash-divshot-cli/), I'm convinced it's the best option. 

The rewrite is a separate package because we'll want to be able to administer remote instances and we shouldn't be using Anvil's internal logic in the tool. It was easy to get started this way, but the code is a bit fragile as a result.

If you have any ideas, it's a good time to discuss since the rewrite is just getting started. Come say hello on [gitter](https://gitter.im/christiansmith/anvil-connect).

**Comment by christiansmith** [comment]
Closing this for now. Let me know if you have further trouble.
